CONST_FIRST_NAME_LENGTH = 20
CONST_LAST_NAME_LENGTH = 20
CONST_NAME_LENGTH = 40
CONST_PASSD_LENGTH = 128
CONST_USERNAME_LENGTH = 20
CONST_MESSAGE_LENGTH = 1000
CONST_ROOM_NAME_LENGTH = 200
CONST_ROOM_TYPE_LENGTH = 20

#choices
CONST_ROOM_TYPE_SINGLE = 'single'
CONST_ROOM_TYPE_GROUP = 'group'
CONST_ROOM_TYPES = (
    (CONST_ROOM_TYPE_SINGLE, CONST_ROOM_TYPE_SINGLE),
    (CONST_ROOM_TYPE_GROUP, CONST_ROOM_TYPE_GROUP),
)